import type { DecisionEvidence, EvidenceRecord, Finding, ProtocolSection, ScenarioMetric } from './types'

export const demoProtocol: ProtocolSection[] = [
  {
    id: 'synopsis',
    label: 'Protocol synopsis',
    text: 'ORBIT-201 is a synthetic demonstration protocol for a randomized Phase 2 study of fictional orvamerib plus pembrolizumab versus pembrolizumab alone in adults with metastatic, MET-altered non-small cell lung cancer.',
  },
  {
    id: 'objective',
    label: '1. Primary objective',
    text: 'The primary objective is to compare progression-free survival at 6 months using investigator-assessed RECIST 1.1. The study is designed to enroll 86 participants across 14 sites in the United States.',
  },
  {
    id: 'population',
    label: '2. Study population',
    text: 'Eligible participants must have received exactly one prior systemic therapy, have an ECOG performance status of 0, measurable disease, and an estimated glomerular filtration rate (eGFR) of at least 60 mL/min/1.73m². Participants with another malignancy within the previous 5 years are excluded.',
  },
  {
    id: 'treatment',
    label: '3. Treatment and monitoring',
    text: 'Participants will receive orvamerib once daily and pembrolizumab every 3 weeks. Clinic visits occur weekly during the first 12 weeks. Dose interruption is permitted for treatment-related toxicity at the investigator’s discretion.',
  },
  {
    id: 'analysis',
    label: '4. Primary analysis',
    text: 'The primary analysis will estimate the progression-free survival rate at 6 months in each arm. Participants without a tumor assessment at 6 months will be considered non-responders.',
  },
]

export const evidenceRecords: EvidenceRecord[] = [
  {
    id: 'geometry-mono1',
    nctId: 'NCT02414139',
    title: 'GEOMETRY mono-1: capmatinib in METex14 NSCLC',
    phase: 'Phase 2',
    status: 'COMPLETED',
    outcome: 'success',
    outcomeLabel: 'Target validated · FDA approval',
    actualEnrollment: 373,
    reason: 'Capmatinib monotherapy produced durable responses in MET exon 14-skipping NSCLC and supported FDA approval.',
    result: 'Final METex14 cohorts reported 68% ORR in treatment-naive patients and 44% ORR in previously treated patients.',
    relevance: 'Direct evidence that MET can be a successful target in the same disease when the population and treatment strategy are aligned.',
    relevanceLabel: 'Same disease + target',
    analogs: ['NSCLC', 'MET target', 'Phase 2', 'ECOG 0–1', 'Monotherapy'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02414139' },
      { label: 'Final results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/39362249/' },
      { label: 'FDA approval record', kind: 'Regulatory', url: 'https://www.accessdata.fda.gov/scripts/opdlisting/oopd/detailedIndex.cfm?cfgridkey=644518' },
    ],
  },
  {
    id: 'vision-tepotinib',
    nctId: 'NCT02864992',
    title: 'VISION: tepotinib in METex14 NSCLC',
    phase: 'Phase 2',
    status: 'ACTIVE_NOT_RECRUITING',
    outcome: 'success',
    outcomeLabel: 'Durable activity · traditional approval',
    actualEnrollment: 337,
    reason: 'VISION confirmed durable activity for MET-targeted monotherapy and supported conversion to traditional FDA approval in 2024.',
    result: 'Among 313 METex14 patients, ORR was 51.4% and median duration of response was 18.0 months.',
    relevance: 'A second successful MET inhibitor in the same biomarker-defined disease, including treatment-naive and previously treated cohorts.',
    relevanceLabel: 'Same disease + target',
    analogs: ['NSCLC', 'MET target', 'Phase 2', 'ECOG 0–1', 'Monotherapy'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02864992' },
      { label: 'Long-term results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/37270698/' },
      { label: 'FDA traditional approval', kind: 'Regulatory', url: 'https://www.fda.gov/drugs/resources-information-approved-drugs/fda-approves-tepotinib-metastatic-non-small-cell-lung-cancer' },
    ],
  },
  {
    id: 'keynote-024',
    nctId: 'NCT02142738',
    title: 'KEYNOTE-024: pembrolizumab in PD-L1-high NSCLC',
    phase: 'Phase 3',
    status: 'COMPLETED',
    outcome: 'success',
    outcomeLabel: 'Primary endpoint met',
    actualEnrollment: 305,
    reason: 'Careful PD-L1 enrichment identified a population in which pembrolizumab outperformed platinum chemotherapy.',
    result: 'Median PFS was 10.3 versus 6.0 months; the hazard ratio for progression or death was 0.50 (P<0.001).',
    relevance: 'Same disease and pembrolizumab backbone; useful evidence for biomarker threshold and comparator choices rather than the MET combination itself.',
    relevanceLabel: 'Same disease + backbone',
    analogs: ['NSCLC', 'PD-1 backbone', 'Phase 3', 'PD-L1 ≥50%', 'Randomized'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02142738' },
      { label: 'Primary results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/27718847/' },
    ],
  },
  {
    id: 'keynote-189',
    nctId: 'NCT02578680',
    title: 'KEYNOTE-189: pembrolizumab plus chemotherapy',
    phase: 'Phase 3',
    status: 'COMPLETED',
    outcome: 'success',
    outcomeLabel: 'OS and PFS endpoints met',
    actualEnrollment: 616,
    reason: 'Pembrolizumab combined with pemetrexed-platinum improved survival in metastatic nonsquamous NSCLC.',
    result: 'Twelve-month OS was 69.2% versus 49.4%; median PFS was 8.8 versus 4.9 months (both P<0.001).',
    relevance: 'Same disease and checkpoint backbone; shows that combination success depends on partner, population, comparator, and safety profile.',
    relevanceLabel: 'Same disease + backbone',
    analogs: ['NSCLC', 'PD-1 backbone', 'Phase 3', 'Combination', 'Randomized'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02578680' },
      { label: 'Primary results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/29658856/' },
    ],
  },
  {
    id: 'capmatinib-pembro',
    nctId: 'NCT04139317',
    title: 'Capmatinib plus pembrolizumab versus pembrolizumab in NSCLC',
    phase: 'Phase 2',
    status: 'TERMINATED',
    outcome: 'stopped',
    outcomeLabel: 'Stopped · tolerability',
    actualEnrollment: 76,
    reason: 'The registry reports insufficient tolerability in the combination arm versus pembrolizumab alone.',
    result: 'The study stopped early; the public registry attributes the decision to combination-arm tolerability.',
    relevance: 'Same disease, phase, immunotherapy backbone, and MET-directed combination.',
    relevanceLabel: 'Closest combination analog',
    analogs: ['NSCLC', 'MET target', 'PD-1 backbone', 'Phase 2', 'Combination'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT04139317' },
    ],
  },
  {
    id: 'nivolumab-combinations',
    nctId: 'NCT02323126',
    title: 'Nivolumab combinations in previously treated NSCLC',
    phase: 'Phase 2',
    status: 'TERMINATED',
    outcome: 'stopped',
    outcomeLabel: 'Stopped · recruitment',
    actualEnrollment: 64,
    reason: 'The sponsor cited low recruitment after the NSCLC treatment landscape changed.',
    result: 'The trial enrolled 64 participants before termination; recruitment was the disclosed reason, not an efficacy result.',
    relevance: 'Same disease and phase; similar targeted-therapy plus checkpoint-inhibitor strategy.',
    relevanceLabel: 'Same strategy',
    analogs: ['NSCLC', 'MET arm', 'PD-1 backbone', 'Phase 2', 'Previously treated'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02323126' },
    ],
  },
  {
    id: 'tepotinib-cns',
    nctId: 'NCT04739358',
    title: 'Tepotinib dose expansion in MET-driven NSCLC',
    phase: 'Phase 1/2',
    status: 'TERMINATED',
    outcome: 'stopped',
    outcomeLabel: 'Stopped · enrollment',
    actualEnrollment: 2,
    reason: 'The registry attributes termination to lack of enrollment and a difficult patient population.',
    result: 'Only 2 participants enrolled; no efficacy conclusion can be drawn from the public record.',
    relevance: 'Same biomarker-defined NSCLC population and MET-directed treatment.',
    relevanceLabel: 'Same narrow population',
    analogs: ['NSCLC', 'MET target', 'CNS population', 'Phase 1/2'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT04739358' },
    ],
  },
  {
    id: 'checkmate-026',
    nctId: 'NCT02041533',
    title: 'CheckMate 026: first-line nivolumab versus chemotherapy',
    phase: 'Phase 3',
    status: 'COMPLETED',
    outcome: 'endpoint-miss',
    outcomeLabel: 'Primary endpoint not met',
    actualEnrollment: 541,
    reason: 'Nivolumab did not significantly improve PFS over chemotherapy in the prespecified PD-L1 ≥5% population.',
    result: 'Median PFS was 4.2 versus 5.9 months; HR 1.15, P=0.25. Overall survival was similar.',
    relevance: 'Same disease and PD-1 mechanism; contrasts with KEYNOTE-024 and highlights the importance of biomarker threshold and trial population.',
    relevanceLabel: 'Same disease + mechanism',
    analogs: ['NSCLC', 'PD-1 mechanism', 'Phase 3', 'PD-L1 ≥5%', 'Randomized'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02041533' },
      { label: 'Primary results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/28636851/' },
    ],
  },
  {
    id: 'mystic',
    nctId: 'NCT02453282',
    title: 'MYSTIC: durvalumab ± tremelimumab versus chemotherapy',
    phase: 'Phase 3',
    status: 'ACTIVE_NOT_RECRUITING',
    outcome: 'endpoint-miss',
    outcomeLabel: 'Primary endpoints not met',
    actualEnrollment: 1118,
    reason: 'Neither durvalumab alone nor durvalumab plus tremelimumab met the prespecified primary survival endpoints.',
    result: 'The combination did not improve OS or PFS versus chemotherapy in the PD-L1 ≥25% primary analysis population.',
    relevance: 'Same disease and checkpoint-combination logic with a different partner target; useful for endpoint, biomarker, and multiplicity design analogies.',
    relevanceLabel: 'Same disease + strategy',
    analogs: ['NSCLC', 'Checkpoint combination', 'Phase 3', 'PD-L1 ≥25%', 'Randomized'],
    sources: [
      { label: 'ClinicalTrials.gov', kind: 'Registry', url: 'https://clinicaltrials.gov/study/NCT02453282' },
      { label: 'Primary results', kind: 'Publication', url: 'https://pubmed.ncbi.nlm.nih.gov/32271377/' },
    ],
  },
]

export const decisionEvidenceRecords: DecisionEvidence[] = [
  {
    id: 'fda-performance-status-2026',
    title: 'Cancer trial performance-status eligibility',
    organization: 'FDA Oncology Center of Excellence',
    year: 2026,
    kind: 'Regulatory guidance',
    relevance: 'Design standard',
    summary: 'Final FDA guidance says performance-status criteria can be more restrictive than necessary and recommends considering a wider performance-status range when appropriate.',
    supports: 'An ECOG 0-only rule needs a documented safety or scientific rationale before excluding ECOG 1.',
    limitation: 'The guidance does not establish a safe ECOG range for any specific regimen.',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/cancer-clinical-trial-eligibility-criteria-performance-status',
  },
  {
    id: 'nsclc-broadened-eligibility',
    title: 'Impact of broader eligibility in advanced NSCLC',
    organization: 'Clinical Cancer Research',
    year: 2021,
    kind: 'Peer-reviewed study',
    relevance: 'Direct precedent',
    summary: 'In 10,500 patients with advanced NSCLC, traditional combined criteria excluded 48%; broader brain-metastasis, prior-malignancy, and renal criteria made 98% potentially eligible.',
    supports: 'Stacked exclusions can sharply contract the candidate pool in the same disease.',
    limitation: 'The analysis bundled three eligibility changes and did not test this protocol or the ECOG rule alone.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/33563634/',
  },
  {
    id: 'ctti-recruitment-framework',
    title: 'Evidence-based recruitment planning framework',
    organization: 'Clinical Trials Transformation Initiative',
    year: 2018,
    kind: 'Peer-reviewed study',
    relevance: 'Supporting context',
    summary: 'CTTI identifies protocol design, feasibility and site selection, and communication as three core parts of strategic recruitment planning.',
    supports: 'A feasibility check should test the combined effect of biomarker, treatment-line, and performance-status rules before launch.',
    limitation: 'This is a planning framework, not an effect estimate for MET-altered NSCLC.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29330082/',
  },
  {
    id: 'capmatinib-pembro-results',
    title: 'Capmatinib plus pembrolizumab Phase 2 results',
    organization: 'Journal of Clinical Oncology',
    year: 2022,
    kind: 'Trial result',
    relevance: 'Direct precedent',
    summary: 'The randomized study reported that the combination was not well tolerated and did not improve antitumor activity over pembrolizumab alone.',
    supports: 'The same-disease, same-backbone combination warrants prospective tolerability controls rather than investigator discretion alone.',
    limitation: 'This was a meeting abstract in a MET-unselected, PD-L1-high population and may not generalize to another biomarker-defined protocol.',
    url: 'https://ascopubs.org/doi/10.1200/JCO.2022.40.16_suppl.9118',
  },
  {
    id: 'fda-ind-safety-elements',
    title: 'Safety elements expected in clinical protocols',
    organization: 'U.S. Food and Drug Administration',
    year: 2026,
    kind: 'Regulatory guidance',
    relevance: 'Design standard',
    summary: 'FDA’s IND protocol resource calls for toxicity monitoring, toxicity-based stopping rules, and dose-adjustment rules, and says these expectations also apply to Phase 2–3 trials.',
    supports: 'The protocol should define pause, stopping, and dose-modification logic in advance.',
    limitation: 'The appropriate thresholds still require product-specific clinical and statistical review.',
    url: 'https://www.fda.gov/drugs/investigational-new-drug-ind-application/ind-applications-clinical-investigations-clinical-protocols',
  },
  {
    id: 'fda-oncology-dosing-toolkit',
    title: 'Oncology dosing and tolerability evidence checklist',
    organization: 'FDA Oncology Center of Excellence',
    year: 2024,
    kind: 'Regulatory guidance',
    relevance: 'Supporting context',
    summary: 'FDA’s dosing toolkit highlights dose-limiting toxicities, interruptions, reductions, discontinuations, and overlapping toxicities in combination regimens.',
    supports: 'A safety lead-in should measure tolerability and overlapping toxicity before full combination enrollment.',
    limitation: 'The toolkit describes evidence to collect; it does not prescribe this trial’s cohort size or DLT window.',
    url: 'https://www.fda.gov/about-fda/oncology-center-excellence/oncology-dosing-tool-kit',
  },
  {
    id: 'fda-organ-dysfunction',
    title: 'Eligibility for patients with organ dysfunction',
    organization: 'U.S. Food and Drug Administration',
    year: 2020,
    kind: 'Regulatory guidance',
    relevance: 'Design standard',
    summary: 'FDA recommends justifying renal exclusions using development stage, safety profile, drug elimination, and procedure risk, and including renal impairment when available data support safe participation.',
    supports: 'The eGFR 60 cutoff should be linked to pharmacology or safety evidence rather than inherited as a template.',
    limitation: 'It does not establish a product-specific cutoff for the regimen under review.',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/cancer-clinical-trial-eligibility-criteria-patients-organ-dysfunction-or-prior-or-concurrent',
  },
  {
    id: 'asco-friends-organ-function',
    title: 'Modernizing organ-function eligibility criteria',
    organization: 'ASCO–Friends of Cancer Research',
    year: 2017,
    kind: 'Peer-reviewed study',
    relevance: 'Supporting context',
    summary: 'The working group recommended including creatinine clearance above 30 mL/min when renal toxicity and renal clearance are not direct treatment concerns.',
    supports: 'A lower threshold is a reasonable option to evaluate if product-specific evidence does not justify 60.',
    limitation: 'This consensus recommendation cannot substitute for the investigational product’s PK and safety data.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28968172/',
  },
  {
    id: 'fda-decentralized-elements',
    title: 'Conducting trials with decentralized elements',
    organization: 'U.S. Food and Drug Administration',
    year: 2024,
    kind: 'Regulatory guidance',
    relevance: 'Design standard',
    summary: 'Final FDA guidance permits appropriate trial activities through telehealth, in-home visits, and local health care providers while retaining oversight and safety requirements.',
    supports: 'Each weekly visit should be decomposed so noncritical activities can be evaluated for local or remote completion.',
    limitation: 'Some examinations, imaging, dosing, and safety assessments may still require a trial site.',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/conducting-clinical-trials-decentralized-elements',
  },
  {
    id: 'protocol-design-performance',
    title: 'Protocol variables predictive of trial performance',
    organization: 'Therapeutic Innovation & Regulatory Science',
    year: 2022,
    kind: 'Peer-reviewed study',
    relevance: 'Supporting context',
    summary: 'Across 187 protocols, operational and scientific design variables—including procedures per visit and eligibility criteria—predicted enrollment, retention, cycle time, and amendments.',
    supports: 'Eligibility and procedure complexity should be tested and simplified before protocol lock.',
    limitation: 'The observational analysis cannot prove that changing any single design feature improves performance.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35094369/',
  },
  {
    id: 'burden-and-withdrawal',
    title: 'Perceived trial burden and cancer-trial withdrawal',
    organization: 'JAMA Network Open',
    year: 2022,
    kind: 'Peer-reviewed study',
    relevance: 'Direct precedent',
    summary: 'In a cancer-trial cohort, a higher perceived burden score was associated with actual withdrawal (adjusted OR 1.86) and a broader withdrawal measure (adjusted OR 3.44).',
    supports: 'Participant burden is a credible retention risk that should be evaluated, not merely an inconvenience.',
    limitation: 'The association does not prove that visit frequency alone caused withdrawal.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/36449287/',
  },
  {
    id: 'phase2-time-burden',
    title: 'Planned time burden in Phase 2 cancer trials',
    organization: 'Cancer Treatment and Research Communications',
    year: 2026,
    kind: 'Peer-reviewed study',
    relevance: 'Direct precedent',
    summary: 'A review of 73 Phase 2 cancer-trial arms found a median of 5 planned research days in month one and 2 per month thereafter.',
    supports: 'Twelve weekly visits should be benchmarked against contemporary Phase 2 oncology schedules and justified assessment by assessment.',
    limitation: 'Cross-trial medians do not determine the clinically necessary schedule for this investigational combination.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/41838412/',
  },
  {
    id: 'fda-e9r1-estimands',
    title: 'E9(R1): Estimands and sensitivity analysis',
    organization: 'FDA / International Council for Harmonisation',
    year: 2021,
    kind: 'Methodology standard',
    relevance: 'Design standard',
    summary: 'E9(R1) requires the clinical question, intercurrent-event strategy, estimator, and sensitivity analyses to align so the reported treatment effect is interpretable.',
    supports: 'Missing imaging, discontinuation, rescue therapy, and death should not be collapsed into one outcome without an estimand rationale.',
    limitation: 'The standard supplies a framework, not the final estimand or model for this protocol.',
    url: 'https://www.fda.gov/regulatory-information/search-fda-guidance-documents/e9r1-statistical-principles-clinical-trials-addendum-estimands-and-sensitivity-analysis-clinical',
  },
  {
    id: 'national-academies-missing-data',
    title: 'Prevention and treatment of missing trial data',
    organization: 'National Academies of Sciences',
    year: 2010,
    kind: 'Methodology standard',
    relevance: 'Supporting context',
    summary: 'The National Academies recommends limiting missing data through design and using analyses that make full use of randomized participants while stating assumptions about missingness.',
    supports: 'The protocol should distinguish why data are missing and predefine sensitivity analyses instead of applying one blanket rule.',
    limitation: 'The report is cross-therapeutic and predates ICH E9(R1).',
    url: 'https://nap.nationalacademies.org/catalog/12955/the-prevention-and-treatment-of-missing-data-in-clinical-trials',
  },
  {
    id: 'nonresponder-imputation-simulation',
    title: 'Simulation of non-responder imputation strategies',
    organization: 'Pharmaceutical Statistics',
    year: 2019,
    kind: 'Peer-reviewed study',
    relevance: 'Supporting context',
    summary: 'A simulation study found that treating every missing response as non-response produced biased estimates, while multiple-imputation approaches generally controlled bias and error better.',
    supports: 'Blanket non-responder assignment needs justification and sensitivity testing against alternative assumptions.',
    limitation: 'The simulation concerned dichotomized continuous outcomes and is not specific to 6-month PFS.',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31345166/',
  },
]

export const demoFindings: Finding[] = [
  {
    id: 'narrow-population',
    category: 'Recruitment',
    severity: 'High',
    title: 'The eligible population may be too narrow',
    sectionId: 'population',
    phrase: 'exactly one prior systemic therapy, have an ECOG performance status of 0',
    explanation: 'A biomarker-defined population is narrowed again by treatment-line and performance-status rules. Closely related MET-driven and checkpoint-combination studies publicly reported recruitment difficulty.',
    suggestion: 'Test ECOG 0–1 and a more flexible prior-therapy rule in a feasibility cohort before finalizing the protocol.',
    replacement: 'one or more prior systemic therapies, have an ECOG performance status of 0 or 1',
    confidence: 'High',
    sourceIds: ['geometry-mono1', 'vision-tepotinib', 'nivolumab-combinations', 'tepotinib-cns'],
    supportIds: ['fda-performance-status-2026', 'nsclc-broadened-eligibility', 'ctti-recruitment-framework'],
    evidenceLabel: '4 analogs · 3 source briefs',
  },
  {
    id: 'combination-tolerability',
    category: 'Safety',
    severity: 'High',
    title: 'Combination tolerability needs an explicit control',
    sectionId: 'treatment',
    phrase: 'Dose interruption is permitted for treatment-related toxicity at the investigator’s discretion.',
    explanation: 'A highly matched Phase 2 MET-directed plus pembrolizumab trial was terminated after tolerability problems in the combination arm. Investigator discretion alone leaves the escalation and stopping logic underspecified.',
    suggestion: 'Add a safety lead-in, dose-limiting toxicity window, and prespecified pause and stopping rules.',
    confidence: 'High',
    sourceIds: ['geometry-mono1', 'vision-tepotinib', 'capmatinib-pembro', 'keynote-189'],
    supportIds: ['capmatinib-pembro-results', 'fda-ind-safety-elements', 'fda-oncology-dosing-toolkit'],
    evidenceLabel: '4 analogs · 3 source briefs',
  },
  {
    id: 'renal-threshold',
    category: 'Eligibility',
    severity: 'Moderate',
    title: 'Renal threshold lacks a stated rationale',
    sectionId: 'population',
    phrase: 'eGFR) of at least 60 mL/min/1.73m²',
    explanation: 'This threshold removes part of the otherwise eligible population, but the draft does not connect it to pharmacology, prior toxicity, or a product-specific safety requirement.',
    suggestion: 'Document the product-specific basis or evaluate a lower threshold with intensified monitoring. Clinical and safety review is required.',
    confidence: 'Needs review',
    sourceIds: [],
    supportIds: ['fda-organ-dysfunction', 'asco-friends-organ-function', 'nsclc-broadened-eligibility'],
    evidenceLabel: '3 source briefs',
  },
  {
    id: 'visit-burden',
    category: 'Operations',
    severity: 'Moderate',
    title: 'Early visit burden may increase dropout',
    sectionId: 'treatment',
    phrase: 'Clinic visits occur weekly during the first 12 weeks.',
    explanation: 'Twelve consecutive weekly visits create a large participant and site burden. The protocol does not explain which assessments require in-person collection.',
    suggestion: 'Map each visit to a safety-critical assessment and test remote or local collection for noncritical procedures.',
    confidence: 'Moderate',
    sourceIds: [],
    supportIds: ['fda-decentralized-elements', 'protocol-design-performance', 'burden-and-withdrawal', 'phase2-time-burden'],
    evidenceLabel: '4 source briefs',
  },
  {
    id: 'endpoint-handling',
    category: 'Endpoint',
    severity: 'Review',
    title: 'Missing assessments are conflated with progression',
    sectionId: 'analysis',
    phrase: 'Participants without a tumor assessment at 6 months will be considered non-responders.',
    explanation: 'Classifying every missing assessment as treatment failure may bias the estimand and does not distinguish progression, treatment discontinuation, withdrawal, or missed imaging.',
    suggestion: 'Specify the estimand, intercurrent-event strategy, censoring rules, and sensitivity analyses before assigning missing outcomes.',
    confidence: 'High',
    sourceIds: ['keynote-024', 'keynote-189', 'checkmate-026', 'mystic'],
    supportIds: ['fda-e9r1-estimands', 'national-academies-missing-data', 'nonresponder-imputation-simulation'],
    evidenceLabel: '4 analogs · 3 source briefs',
  },
]

export const scenarioMetrics: ScenarioMetric[] = [
  { label: 'Candidate pool index', before: '100', after: '118', direction: 'up' },
  { label: 'Enrollment estimate', before: '17.8 mo', after: '15.1 mo', direction: 'down' },
  { label: 'Screen-failure index', before: '100', after: '84', direction: 'down' },
]
